# Site settings
title: "Jekyll Resume Template"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "David Bazalar"
resume_title:                   "Civil Engineer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "davidbazalar@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "705-5623854"
resume_contact_address:         "2-400 Ramsey Road, Sudbury"

resume_header_contact_info:     "2-400 Ramsey Road, Sudbury • 705-5623854 • davidbazalar@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>My main professional objective is to further develop my competence in the use of applied mathematical tools and scientific computing to enhance the way we learn from the opaque rockmass and specify models that provide greater input and reliability to the production schedule.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/dbazalar/resume-template"
  #resume_twitter_url:           "http://twitter.com/DavidBazalar"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  #resume_linkedin_url:          "https://www.linkedin.com/in/davidbazalar"
  # resume_instagram_url:         "insert your Instagram URL here"
  #resume_website_url:           "http://davidbazalar.com"
  #resume_medium_url:            "https://medium.com/@davidbazalar"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
